import { Header } from "@src/app/ui/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tokopaedi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />

        <main className="mx-auto flex min-h-screen max-w-7xl flex-col items-center justify-center font-sans">
          <div className="flex size-full min-h-screen flex-col items-center justify-between px-4 pt-18 pb-22 sm:items-start md:py-32">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
